name: beike_aspectd
description: AOP for Flutter. AspectD is an AOP(aspect oriented programming) framework for dart. It provides call&execute&inject grammar.
version: 0.9.7
homepage: https://github.com/alibaba-flutter/aspectd

environment:
  sdk: ">=2.3.0-dev.68.0 <3.0.0"

dev_dependencies:

  args: any
  path: any
  yaml: any

dependency_overrides:

  package_config: 1.9.3

  meta:
    path: ../../sdk/pkg/meta

  frontend_server:
    path: ../../../SDK/sdk/pkg/frontend_server

  _fe_analyzer_shared:
    path: ../../../SDK/sdk/pkg/_fe_analyzer_shared

  vm:
    path: ../../../SDK/sdk/pkg/vm

  kernel:
    path: ../../../SDK/sdk/pkg/kernel
